In [ ]:
import pandas as pd

In [27]:
#Load in 2022-2023 Regular Season Data

#Link: https://www.basketball-reference.com/leagues/NBA_2023_advanced.html

# Read the CSV file into a DataFrame
reg22_23 = pd.read_csv("2022-2023reg.csv")

reg22_23.head()

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP,Player-additional
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9999
1,1.0,Precious Achiuwa,C,23.0,TOR,55.0,1140.0,15.2,0.554,0.267,...,0.8,1.4,2.2,0.093,NaN,-1.4,-0.8,-2.3,-0.1,achiupr01
2,2.0,Steven Adams,C,29.0,MEM,42.0,1133.0,17.5,0.564,0.004,...,1.3,2.1,3.4,0.144,NaN,-0.3,0.9,0.6,0.7,adamsst01
3,3.0,Bam Adebayo,C,25.0,MIA,75.0,2598.0,20.1,0.592,0.011,...,3.6,3.8,7.4,0.137,NaN,0.8,0.8,1.5,2.3,adebaba01
4,4.0,Ochai Agbaji,SG,22.0,UTA,59.0,1209.0,9.5,0.561,0.591,...,0.9,0.4,1.3,0.053,NaN,-1.7,-1.4,-3.0,-0.3,agbajoc01

In [28]:
#Clean Data

reg22_23.drop(index = 0, inplace = True)

columns_to_drop = ["Unnamed: 19", "Unnamed: 24", "Player-additional", "Rk"]

reg22_23.drop(columns=columns_to_drop, axis=1, inplace=True)

In [29]:
#Look at clean data- Looks good!

reg22_23.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
1,Precious Achiuwa,C,23.0,TOR,55.0,1140.0,15.2,0.554,0.267,0.307,...,11.4,19.4,0.8,1.4,2.2,0.093,-1.4,-0.8,-2.3,-0.1
2,Steven Adams,C,29.0,MEM,42.0,1133.0,17.5,0.564,0.004,0.490,...,19.8,14.6,1.3,2.1,3.4,0.144,-0.3,0.9,0.6,0.7
3,Bam Adebayo,C,25.0,MIA,75.0,2598.0,20.1,0.592,0.011,0.361,...,12.7,25.2,3.6,3.8,7.4,0.137,0.8,0.8,1.5,2.3
4,Ochai Agbaji,SG,22.0,UTA,59.0,1209.0,9.5,0.561,0.591,0.179,...,9.0,15.8,0.9,0.4,1.3,0.053,-1.7,-1.4,-3.0,-0.3
5,Santi Aldama,PF,22.0,MEM,77.0,1682.0,13.9,0.591,0.507,0.274,...,9.3,16.0,2.1,2.4,4.6,0.130,-0.3,0.8,0.5,1.1

In [30]:
#Load in 2022-2023 Playoff Data

#Link: https://www.basketball-reference.com/playoffs/NBA_2023_advanced.html

# Read the CSV file into a DataFrame
playoff22_23 = pd.read_csv("2022-2023playoff.csv")

playoff22_23.head()

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP,Player-additional
0,1,Bam Adebayo,C,25,MIA,23,850,15.8,0.530,0.009,...,0.3,1.1,1.4,0.078,NaN,-1.2,0.6,-0.6,0.3,adebaba01
1,2,Santi Aldama,PF,22,MEM,6,101,15.0,0.576,0.455,...,0.2,0.1,0.3,0.139,NaN,2.3,1.7,4.0,0.2,aldamsa01
2,3,Nickeil Alexander-Walker,SG,24,MIN,5,148,7.7,0.578,0.714,...,0.0,0.0,0.0,0.011,NaN,-1.9,0.0,-1.9,0.0,alexani01
3,4,Grayson Allen,SG,27,MIL,5,149,11.0,0.658,0.707,...,0.2,0.0,0.2,0.073,NaN,-0.2,-1.0,-1.1,0.0,allengr01
4,5,Jarrett Allen,C,24,CLE,5,191,13.9,0.608,0.000,...,0.3,0.3,0.6,0.150,NaN,0.6,1.8,2.4,0.2,allenja01

In [31]:
#Clean Data

columns_to_drop = ["Unnamed: 19", "Unnamed: 24", "Player-additional", "Rk"]

playoff22_23.drop(columns=columns_to_drop, axis=1, inplace=True)

In [32]:
#Look at clean data- Looks good!

playoff22_23.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Bam Adebayo,C,25,MIA,23,850,15.8,0.530,0.009,0.274,...,13.8,23.8,0.3,1.1,1.4,0.078,-1.2,0.6,-0.6,0.3
1,Santi Aldama,PF,22,MEM,6,101,15.0,0.576,0.455,0.061,...,5.6,14.9,0.2,0.1,0.3,0.139,2.3,1.7,4.0,0.2
2,Nickeil Alexander-Walker,SG,24,MIN,5,148,7.7,0.578,0.714,0.086,...,9.9,12.6,0.0,0.0,0.0,0.011,-1.9,0.0,-1.9,0.0
3,Grayson Allen,SG,27,MIL,5,149,11.0,0.658,0.707,0.171,...,8.3,13.6,0.2,0.0,0.2,0.073,-0.2,-1.0,-1.1,0.0
4,Jarrett Allen,C,24,CLE,5,191,13.9,0.608,0.000,0.167,...,7.2,10.2,0.3,0.3,0.6,0.150,0.6,1.8,2.4,0.2